### ISSUE TITLE
Issue with GitHub Action: Trigger repository dispatch on Pangeo Gallery

### ISSUE THREAD

**Issue by salvis2** [pangeo-gallery/pangeo-gallery#18]
I am trying to integrate `pangeo-tutorial` content into `pangeo-gallery`. I have build a repo [here](https://github.com/pangeo-data/pangeo-tutorial-gallery) according to the [Contributor Guide](http://gallery.pangeo.io/contributing.html). In pushing my changes, the GitHub Action fails in [this build](https://github.com/pangeo-data/pangeo-tutorial-gallery/runs/740649393?check_suite_focus=true). The erroring logs are here in the Trigger repository dispatch on Pangeo Gallery:

```
Run curl -f https://pangeo-gallery-bot.herokuapp.com/gallery/submodule-dispatch/pangeo-data/pangeo-tutorial-gallery
  curl -f https://pangeo-gallery-bot.herokuapp.com/gallery/submodule-dispatch/pangeo-data/pangeo-tutorial-gallery
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.3/x64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0
curl: (22) The requested URL returned error: 500 Internal Server Error
##[error]Process completed with exit code 22.
```

I would like some help in figuring out what to do with this.

**Comment by rabernat** [comment]
This is an error from the tiny bot we built to trigger the gallery to rebuild: https://pangeo-gallery-bot.herokuapp.com/docs

I think it is failing because this repo doesn't yet have your gallery in it. I think the following should start that process:

/add-submodule pangeo-data/pangeo-tutorial-gallery

**Comment by rabernat** [comment]
@andersy005 -- do you have any idea why the command is not having any effect?

**Comment by andersy005** [comment]
> @andersy005 -- do you have any idea why the command is not having any effect? 

I am about to look into it

**Comment by andersy005** [comment]
> do you have any idea why the command is not having any effect?

The comment is not having any effect because the workflow is trigger when an issue is opened only:

https://github.com/pangeo-gallery/pangeo-gallery/blob/59defb15e6256b61f8120c17289d788f736b9122/.github/workflows/add-submodule.yml#L2-L5

I opened a new issue: https://github.com/pangeo-gallery/pangeo-gallery/issues/21 and things seems to be working fine. 


Should we change the trigger to be:

```yaml
on:
  issue_comment:
    types:
       - created
        - edited
```

???

**Comment by salvis2** [comment]
That will probably trigger an action for every edit to an issue, yeah?

**Comment by andersy005** [comment]
> That will probably trigger an action for every edit to an issue, yeah?

Yeah, and that's why I originally restricted it to issue:opened
