### ISSUE TITLE
Add Pangeo-Tutorial Submodule

### ISSUE THREAD

**Issue by salvis2** [pangeo-gallery/pangeo-gallery#19]
/add-submodule pangeo-data/pangeo-tutorial-gallery

**Comment by andersy005** [comment]
When I created #21, I hadn't noticed you beat me to it😀

**Comment by salvis2** [comment]
Yeah! I figured it was a quick thing to try and then you did it a minute later. I think the second one had it's GitHub Action fail, but the PR was opened so no big deal.
