### ISSUE TITLE
Add xgcm-examples

### ISSUE THREAD

**Issue by jbusecke** [pangeo-gallery/pangeo-gallery#38]
/add-submodule xgcm/xgcm-examples

**Comment by TomAugspurger** [comment]
Hmm, I see that this was supposed to create a pull request. I'm guessing that I broke this while messing with the testing stuff.

**Comment by jbusecke** [comment]
Is there a way to retrigger? 

I have been running into issues with the [binderbot gh action](). From the [docs](https://gallery.pangeo.io/contributing.html#creating-a-new-gallery) "The build may fail to complete before the repo is added as a submodule to pangeo-gallery." I figured Ill try to add it as a submodule first, before actually fleshing out the repo.
Is that the recommended workflow? The 'xgcm-examples' is currently only a dummy.

**Comment by rabernat** [comment]
Once you fix https://github.com/xgcm/xgcm-examples/issues/1, try closing this and opening a new, identical issue. #39 might have fixed this issue.

**Comment by jbusecke** [comment]
Ok great. The bot was triggered in #44
