### ISSUE TITLE
update-gallery failed

### ISSUE THREAD

**Issue by jkingslake** [pangeo-gallery/pangeo-gallery#58]
update-gallery seems to have failed at a stage unrelated to the new changes I made to this [repo](https://github.com/ldeo-glaciology/pangeo-glaciology-examples) that triggered the build:
https://github.com/pangeo-gallery/pangeo-gallery/runs/2731793209?check_suite_focus=true 

It failed at the "Build Sphinx HTML" inside conf.py. It says it saved the traceback in /tmp/sphinx-err-0f8r3yz4.log but I don't know where this is referring to.

**Comment by rabernat** [comment]
Thanks for reporting. Sounds like a sphinx version error. We should probably be pinning our dependencies here:

https://github.com/pangeo-gallery/pangeo-gallery/blob/ce6c72e5ac279974472a082bb6973f9cc70ec196/requirements.txt#L1-L13

**Comment by rabernat** [comment]
Identical issue: https://github.com/sphinx-doc/sphinx/issues/7747
