### ISSUE TITLE
Handle notebooks in subdirectories.

### ISSUE THREAD

**Issue by rabernat** [pangeo-gallery/pangeo-gallery#8]
The NCAR gallery added by @andersy005 in #7 contains the notebooks in a subdirectory. Unfortunately our current config assumes that the notebooks are in the top level directory. Here is how we generate the toctree:

https://github.com/pangeo-gallery/pangeo-gallery/blob/28f39744eba6452bfbeaf3ae958d9693b48705be/build_repo_index_pages.py#L35-L43

Should be a simple fix.

**Comment by andersy005** [comment]
I will submit a PR to address this (unless someone beats me to it :) )

**Comment by rabernat** [comment]
It might be as simple as `**` instead of `*`.
